CREATE TABLE user_info(
    USER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    USER_EMAIL VARCHAR(100) NOT NULL,
    BLOG_ID CHAR(4),
    PRIMARY KEY(USER_ID)
);

CREATE TABLE session_info (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_ip VARCHAR(255),
    user_email VARCHAR(255),
    page VARCHAR(50),
    access_time DATETIME
);
